export const TOOLKIT_ASSETS = {
  shield: '/images/toolkit/shield.svg',
  wrapTab: '/images/toolkit/wrap-tab.svg',
  dnsTab: '/images/toolkit/dns-tab.svg',
  encryptTab: '/images/toolkit/encrypt-tab.svg',
  revokeTab: '/images/toolkit/revoke-tab.svg',
  wrapIcon: '/images/toolkit/wrap-icon.svg',
  lockIcon: '/images/toolkit/lock-icon.svg',
  search: '/images/toolkit/search.svg',
  copy: '/images/toolkit/copy.svg',
  trash: '/images/toolkit/trash.svg',
  download: '/images/toolkit/download.svg',
  runArrow: '/images/toolkit/run-arrow.svg',
  checkCircle: '/images/toolkit/check-circle.svg',
  refresh: '/images/toolkit/refresh.svg',
  attention: '/images/toolkit/attention.svg',
  revokeError: '/images/toolkit/revoke-error.svg',
  regenerate: '/images/toolkit/regenerate.svg',
  warningTriangle: '/images/toolkit/warning-triangle.svg',
  errorX: '/images/toolkit/error-x.svg',
  metamask: '/images/toolkit/metamask.png',
  information: '/images/toolkit/information.svg',
} as const
